spring:
  application:
    name: zemoga-web-app
  datasource:
    url: jdbc:mysql://*
    username: *
    password: *
    driverClassName: com.mysql.jdbc.Driver
  jpa:
    hibernate.ddl-auto: update
    generate-ddl: true
    show-sql: true
    properties:
      hibernate:
        dialect: org.hibernate.dialect.MySQL5Dialect

twitter:
  zemoga:
    consumer-key: *
    consumer-secret: *
    access-tokens: *
    access-token-secret: *

logging:
  file:
    name: logs/zemoga-web-app.log
  level:
    org:
      hibernate:
        SQL: debug
        type:
          descriptor:
            sql: trace