spring:
  application:
    name: zemoga-web-app
  datasource:
    url: jdbc:mysql://localhost:3306/db
    username: *
    password: *
    driverClassName: com.mysql.jdbc.Driver
  jpa:
    hibernate.ddl-auto: update
    generate-ddl: true
    show-sql: true
    properties:
      hibernate:
        dialect: org.hibernate.dialect.MySQL5Dialect
  thymeleaf: # Thymeleaf
    cache: false
    mode: HTML
    encoding: UTF-8
    prefix: file:src/main/resources/templates/

twitter:
  zemoga:
    consumer-key: *
    consumer-secret: *
    access-tokens: *
    access-token-secret: *

portfolio:
  account-id: 14

logging:
  file:
    name: logs/zemoga-web-app.log
  level:
    org:
      hibernate:
        SQL: debug
        type:
          descriptor:
            sql: trace